# Generated by Django 5.2.7 on 2025-10-12 15:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('client_uuid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('android', 'Android'), ('ios', 'iOS'), ('browser', 'Browser'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('os_version', models.CharField(blank=True, default='', max_length=64)),
                ('app_version', models.CharField(blank=True, default='', max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=64)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices_snapshot', to='landing.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_seen',),
                'constraints': [models.UniqueConstraint(fields=('user', 'client_uuid'), name='uniq_user_client_uuid')],
            },
        ),
    ]
