# Generated by Django 5.2.7 on 2026-09-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_extensionlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='source',
            field=models.CharField(default='crypto', max_length=16),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
