# Generated by Django 5.2.7 on 2026-09-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_playpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sadece panelde gorunur', max_length=120)),
                ('media_type', models.CharField(choices=[('image', 'Gorsel'), ('video', 'Video')], db_index=True, default='image', help_text='Video sessiz baslar: tarayicilar sesli otomatik oynatmayi engeller.', max_length=8)),
                ('image_url', models.URLField(help_text='Gorsel icin .png/.jpg, video icin .mp4/.webm. Ornek: https://vpnsterr.com/static/img/ads/x.mp4', max_length=500)),
                ('click_url', models.URLField(help_text='Tiklaninca acilacak https adres', max_length=500)),
                ('alt', models.CharField(blank=True, default='', help_text='Erisilebilirlik metni', max_length=120)),
                ('sponsor', models.CharField(blank=True, default='', help_text="'Sponsored by ...'", max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('weight', models.PositiveIntegerField(default=1, help_text='Buyuk olan daha sik gosterilir')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RenameIndex(
            model_name='playpurchase',
            new_name='landing_pla_user_id_1bf10a_idx',
            old_name='landing_pla_user_id_e6a4d1_idx',
        ),
        migrations.AddIndex(
            model_name='extensionad',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='landing_ext_is_acti_d9f915_idx'),
        ),
    ]
