# Generated by Django 5.2.7 on 2026-09-12 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, unique=True)),
                ('search_volume', models.PositiveIntegerField(blank=True, help_text='Aylık arama hacmi', null=True)),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, help_text='KD 0-100', null=True)),
                ('intent', models.CharField(blank=True, choices=[('buy', 'Buy / transactional'), ('commercial', 'Commercial investigation'), ('free', 'Free-seeking'), ('info', 'Informational'), ('competitor', 'Competitor'), ('geo', 'Geo / location')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'keywords',
                'ordering': ['-search_volume', 'keyword'],
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('accent', models.CharField(choices=[('sky', 'Sky'), ('fuchsia', 'Fuchsia'), ('indigo', 'Indigo'), ('emerald', 'Emerald'), ('amber', 'Amber'), ('rose', 'Rose'), ('teal', 'Teal'), ('violet', 'Violet')], default='sky', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.blogcategory')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('body', models.TextField(blank=True, help_text='HTML')),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=165)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots', models.CharField(choices=[('index,follow', 'index, follow'), ('noindex,nofollow', 'noindex, nofollow'), ('noindex,follow', 'noindex, follow')], default='index,follow', max_length=60)),
                ('focus_keyword', models.CharField(blank=True, max_length=200)),
                ('schema_type', models.CharField(choices=[('BlogPosting', 'BlogPosting'), ('Article', 'Article'), ('FAQPage', 'FAQPage'), ('HowTo', 'HowTo'), ('NewsArticle', 'NewsArticle')], default='BlogPosting', max_length=30)),
                ('json_ld', models.TextField(blank=True)),
                ('featured_image_url', models.URLField(blank=True)),
                ('og_image_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=100)),
                ('og_description', models.CharField(blank=True, max_length=200)),
                ('featured', models.BooleanField(default=False, help_text='Blog ana sayfasında büyük kart')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('seo_score_cache', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('reading_time', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.blogcategory')),
                ('keywords', models.ManyToManyField(blank=True, to='blog.blogkeyword')),
            ],
            options={
                'verbose_name_plural': 'blog posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='blog_blogpo_status_aa5436_idx'), models.Index(fields=['category', 'status'], name='blog_blogpo_categor_2e8dab_idx')],
            },
        ),
    ]
