# Generated by Django 5.2.7 on 2026-09-30 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('first_used_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField()),
                ('last_used_date', models.DateField()),
                ('use_days', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'premium usage',
                'verbose_name_plural': 'premium usage',
            },
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_snapshot', models.PositiveIntegerField(db_index=True)),
                ('email_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('account_created_at', models.DateTimeField(blank=True, null=True)),
                ('account_deleted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('stripe_customer_ids', models.TextField(blank=True, default='')),
                ('stripe_subscription_ids', models.TextField(blank=True, default='')),
                ('subscriptions', models.JSONField(blank=True, default=list)),
                ('orders', models.JSONField(blank=True, default=list)),
                ('first_paid_at', models.DateTimeField(blank=True, null=True)),
                ('last_period_end', models.DateTimeField(blank=True, null=True)),
                ('premium_first_used_at', models.DateTimeField(blank=True, null=True)),
                ('premium_last_used_at', models.DateTimeField(blank=True, null=True)),
                ('premium_use_days', models.PositiveIntegerField(default=0)),
                ('device_count', models.PositiveIntegerField(default=0)),
                ('device_last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ('-account_deleted_at',),
                'indexes': [models.Index(fields=['email_sha256', '-account_deleted_at'], name='retention_b_email_s_e70aaf_idx')],
            },
        ),
    ]
