# Feature detay sayfaları — tek şablon (feature_detail.html) bu sözlükten beslenir.
# Her sayfa GERÇEK içerik taşır (doorway/spam değil): benzersiz anlatım + SSS + hedef keyword'ler.
# Hedef keyword'ler docs/seo/keyword-map.md'deki kümelerden seçildi.

FEATURES = {
    "no-logs": {
        "name": "Zero Logs",
        "icon": "shield",
        "hue": "fuchsia",
        "meta_title": "No-Logs VPN — Zero Activity Logs, By Design | VPNsterr",
        "meta_description": "VPNsterr is a strict no-logs VPN: no browsing history, no DNS queries, no IP records. See exactly what zero logs means — and how our free tier proves it.",
        "h1": "A no-logs VPN, by architecture — not by promise",
        "intro": "Every VPN says \"no logs.\" The difference is whether the system is built so logs can't exist in the first place. VPNsterr's network is designed so that your identity and your activity are never stored together — there is no browsing history to leak, sell or hand over, because it is never written down.",
        "sections": [
            ("What \"zero logs\" actually covers",
             "We do not record the websites you visit, your DNS queries, the contents or size patterns of your traffic, your originating IP after a connection is established, or timestamps that could tie a session to your identity. Shared exit IPs mean hundreds of users appear behind the same address, so even network-level observation can't single you out."),
            ("The strongest proof: our free tier needs no account",
             "The free VPNsterr extension works without an email, login or payment method. When a provider doesn't know who you are, it structurally cannot build a profile of what you do. That's a stronger privacy guarantee than any marketing claim."),
            ("What we do keep (and why it can't identify your browsing)",
             "Premium accounts require an email and a subscription status — that's how we deliver what you paid for. Operationally we see aggregate server load and authentication events. None of these link to browsing activity, and there is no mechanism to join them to traffic data."),
        ],
        "bullets": [
            "No browsing history, ever written to disk",
            "No DNS query logging",
            "No source-IP retention after connection",
            "Shared exit IPs separate identity from activity",
            "Free tier works with no account at all",
        ],
        "faq": [
            ("If police request my browsing data, what do you hand over?",
             "Nothing that describes your activity — it doesn't exist. We can only confirm whether an email address has a subscription, because that's all we store."),
            ("Is the no-logs policy the same on the free tier?",
             "Identical. Free and Premium run on the same zero-log architecture; Premium only adds speed, premium servers and removes ads."),
        ],
        "keywords": "no logs vpn, best vpn no logs, private vpn, most private vpn 2026",
    },
    "anonymous-vpn": {
        "name": "100% Anonymous",
        "icon": "user",
        "hue": "sky",
        "meta_title": "Anonymous VPN — Hide Your IP & Identity | VPNsterr",
        "meta_description": "Stay 100% anonymous online: masked IP, shared exit nodes and a VPN that never links who you are to what you do. Try it free — no account needed.",
        "h1": "Anonymity means your identity never touches your activity",
        "intro": "Hiding your IP is step one. Real anonymity is architectural: the system must be unable to connect the person paying for the service with the traffic flowing through it. VPNsterr is engineered around that separation.",
        "sections": [
            ("Masked IP and shared exit nodes",
             "When you connect, websites see one of our shared exit IPs — an address used simultaneously by many users. Your real IP stays between you and the encrypted tunnel, and we don't retain it after the connection is established. There is no per-user address to trace back."),
            ("Anonymous by default on the free tier",
             "The free extension asks for no email, no name, no card. You install it and connect — we never learn who you are. Even Premium can be paid with cryptocurrency, keeping your financial identity out of the picture."),
            ("What anonymity doesn't cover",
             "Honesty matters: if you log into your Google account through any VPN, Google knows it's you. A VPN anonymizes the network layer — pairing it with sensible browsing habits is what keeps you genuinely anonymous."),
        ],
        "bullets": [
            "Your real IP is hidden from every site you visit",
            "Shared exit IPs — you're one of a crowd, by design",
            "No account required on the free tier",
            "Crypto payments keep billing anonymous on Premium",
            "WebRTC leak blocking stops browser-level IP leaks",
        ],
        "faq": [
            ("Can VPNsterr see what I do online?",
             "The tunnel is encrypted and our zero-log architecture never stores activity. We couldn't reconstruct your browsing even under compulsion — the data doesn't exist."),
            ("Is a free anonymous VPN really possible?",
             "Yes, if the business model doesn't depend on your data. Ours doesn't: the free tier is ad-supported without behavioral profiling, and Premium subscriptions fund the network."),
        ],
        "keywords": "anonymous vpn, most anonymous vpn, hide ip vpn, vpn hider",
    },
    "kill-switch": {
        "name": "Kill Switch",
        "icon": "power",
        "hue": "rose",
        "meta_title": "VPN Kill Switch — Zero Leaks If the VPN Drops | VPNsterr",
        "meta_description": "VPNsterr's always-on Kill Switch cuts traffic the instant your VPN connection drops — no IP or DNS leaks, ever. Included free on every plan.",
        "h1": "If the tunnel drops, the traffic stops",
        "intro": "The most dangerous moment for any VPN user is the half-second when a connection drops and the device silently falls back to the open internet. VPNsterr's Kill Switch exists for exactly that moment: connectivity is cut instantly until the tunnel is re-established, so your real IP and DNS never leak.",
        "sections": [
            ("How the Kill Switch works",
             "The Kill Switch sits between your apps and the network. While the VPN is healthy, traffic flows through the encrypted tunnel. The instant the tunnel fails — Wi-Fi handover, network change, server hiccup — the switch blocks outbound traffic at the network layer rather than letting it escape unencrypted. Reconnection is automatic, and traffic resumes only inside the tunnel."),
            ("Why it matters on every network",
             "On café Wi-Fi a drop exposes your traffic to whoever runs the hotspot. On home networks it exposes your real IP to every site with an open connection. With torrent clients or long-lived sessions, even a one-second gap is enough to reveal your address. The Kill Switch turns all of those from an exposure into a non-event."),
            ("Paired with leak protection",
             "The Kill Switch works alongside DNS-leak prevention and WebRTC leak blocking, closing the three most common ways a \"protected\" user actually gets exposed."),
        ],
        "bullets": [
            "Instant traffic cut on tunnel failure — no fallback to open internet",
            "Automatic reconnect, traffic resumes only inside the tunnel",
            "Covers IP, DNS and WebRTC leak paths",
            "Always-on: no configuration needed",
            "Included on free and Premium alike",
        ],
        "faq": [
            ("Will the Kill Switch interrupt my downloads?",
             "It pauses traffic only while the tunnel is down — usually a moment — then everything resumes automatically inside the encrypted connection."),
            ("Do I need to enable it?",
             "No. It ships enabled because a kill switch you forgot to turn on protects nobody."),
        ],
        "keywords": "vpn kill switch, best vpn kill switch, vpn leak protection",
    },
    "ad-blocker": {
        "name": "Ad & Tracker Blocker",
        "icon": "block",
        "hue": "indigo",
        "meta_title": "VPN with Built-In Ad Blocker & Tracker Blocking | VPNsterr",
        "meta_description": "Block ads and trackers on-device with VPNsterr — cleaner pages, faster loads, fewer eyes on you. No extra extensions needed. Free to use.",
        "h1": "Block ads and trackers before they ever load",
        "intro": "Ads aren't just noise — the tracking behind them is a parallel surveillance network. VPNsterr ships a built-in ad and tracker blocker, so you don't need to stack a second extension: cleaner pages, faster loads and fewer parties watching, all in the same click that hides your IP.",
        "sections": [
            ("On-device blocking, not another middleman",
             "Our browser extension uses the browser's own declarativeNetRequest engine: filter rules run inside your browser and block requests to ad and tracker domains before they leave your machine. Blocked-request decisions are never transmitted to us — blocking happens entirely on-device."),
            ("Why blocking trackers matters more than hiding ads",
             "The average news page calls out to dozens of third-party trackers that fingerprint your browser and follow you across sites. Blocking them doesn't just tidy the page — it removes the data trail advertisers use to rebuild your identity even behind a VPN."),
            ("Faster pages as a side effect",
             "Ads and trackers routinely account for a large share of a page's transferred bytes. Blocking them cuts data usage and speeds up page loads — noticeable on slower connections and metered plans."),
        ],
        "bullets": [
            "Blocks ad and tracker domains at the request level",
            "Runs on-device — block decisions never leave your browser",
            "No extra ad-block extension needed",
            "Faster page loads, lower data usage",
            "Toggle on or off per your preference",
        ],
        "faq": [
            ("Does the ad blocker send my browsing data anywhere?",
             "No. Filtering runs inside your browser via declarativeNetRequest; we never receive which pages you visit or which requests were blocked."),
            ("Will sites that block ad-blockers still work?",
             "You can toggle blocking off for any site in one click and keep the VPN protection running."),
        ],
        "keywords": "vpn with ad blocker, vpn to block ads, vpn extension no ads",
    },
    "speed": {
        "name": "1000 Gbps Network",
        "icon": "zap",
        "hue": "amber",
        "meta_title": "High-Speed VPN — 1000 Gbps Backbone | VPNsterr",
        "meta_description": "VPNsterr runs on a 1000 Gbps network core built for peak throughput and low jitter — streaming, gaming and downloads without the VPN slowdown.",
        "h1": "A VPN that doesn't feel like one",
        "intro": "The classic VPN complaint is speed. We built the network backwards from that complaint: a 1000 Gbps backbone, modern protocols and capacity headroom, so encryption overhead — not congestion — is the only thing between you and your line speed.",
        "sections": [
            ("What 1000 Gbps of core capacity buys you",
             "Most VPN slowdowns aren't cryptography — they're crowded servers. Our backbone is provisioned with deliberate headroom, so peak-hour Netflix, game patches and large downloads don't queue behind other users' traffic. The result is high throughput with low jitter, which matters as much for a stable video call as raw bandwidth does for a download."),
            ("WireGuard and modern cryptography",
             "VPNsterr connects over WireGuard and OpenVPN with AES-256 and ChaCha20. WireGuard's lean design costs single-digit percentages of throughput on modern hardware — which is why our users typically can't tell the VPN is on."),
            ("Free vs Premium speed, honestly",
             "The free extension runs at standard speed on shared capacity — genuinely usable, all day, unlimited. Premium unlocks maximum speed on the full backbone plus premium server locations. That difference funds the network; it's the whole business model."),
        ],
        "bullets": [
            "1000 Gbps backbone with deliberate capacity headroom",
            "WireGuard & OpenVPN, AES-256 / ChaCha20",
            "Low jitter for calls and gaming, not just big downloads",
            "Unlimited bandwidth on every tier — no data caps",
            "Premium unlocks maximum speed and premium locations",
        ],
        "faq": [
            ("How much speed will I lose with the VPN on?",
             "On Premium with WireGuard, most users measure within a few percent of their line speed. The free tier runs at standard speed — still unlimited, with no data cap."),
            ("Is bandwidth really unlimited on the free plan?",
             "Yes. No caps, no trial timers, no monthly quota. Speed is standard; volume is unlimited."),
        ],
        "keywords": "high speed vpn, fast vpn, vpn high speed, high performance vpn",
    },
    "per-tab-routing": {
        "name": "Per-Tab Routing",
        "icon": "tabs",
        "hue": "violet",
        "meta_title": "Per-Tab VPN Routing for Chrome | VPNsterr",
        "meta_description": "Route one browser tab through the VPN while another stays on your local connection — VPNsterr's per-tab routing is unique to our Chrome extension.",
        "h1": "One tab through the VPN. Another on your local network. Same browser.",
        "intro": "Sometimes you need a VPN for one site and your real location for another — banking at home while researching abroad, or watching a stream while using a local service. Per-tab routing lets each browser tab decide, simultaneously, with no reconnecting.",
        "sections": [
            ("How per-tab routing works",
             "The VPNsterr extension can scope the proxy to specific tabs instead of the whole browser. Tab A routes through your chosen VPN location; Tab B talks to the internet directly. Both run at the same time — no toggling, no dropped sessions, no juggling two browsers."),
            ("Split tunneling, but easier",
             "Desktop VPNs offer app-level split tunneling that takes a settings page to configure. Per-tab routing brings the same idea to where you actually live — the browser — with a one-click decision per tab."),
            ("Where it shines",
             "Compare prices across regions in two tabs at once. Keep a local-only service (banking, delivery, government portals) on your real connection while everything else stays private. Test geo-specific content as a developer or marketer without a second machine."),
        ],
        "bullets": [
            "Choose per tab: VPN or direct connection",
            "Both run simultaneously — no reconnecting",
            "Rare among VPN extensions; standard in VPNsterr",
            "Perfect for region testing, banking and streaming side-by-side",
            "Works in Chrome, Edge, Brave and other Chromium browsers",
        ],
        "faq": [
            ("Do other VPN extensions offer per-tab routing?",
             "Very few. Most route the entire browser or nothing — per-tab control is one of VPNsterr's genuinely distinctive features."),
            ("Is per-tab routing available on the free tier?",
             "Yes — it's part of the extension itself, free and Premium alike."),
        ],
        "keywords": "per tab vpn, vpn per tab routing, split tunneling browser extension",
    },
    "auto-connect": {
        "name": "Auto-Connect",
        "icon": "refresh",
        "hue": "emerald",
        "meta_title": "VPN Auto-Connect & Auto-Reconnect | VPNsterr",
        "meta_description": "VPNsterr connects the moment your browser starts and reconnects automatically after every drop — protection you never have to remember.",
        "h1": "Protection you never have to remember to turn on",
        "intro": "The most common VPN failure isn't technical — it's human. You forgot to click connect. VPNsterr removes the human step: it connects when your browser starts and reconnects automatically whenever a network change knocks the tunnel down.",
        "sections": [
            ("Connect on startup",
             "Enable auto-connect and the extension establishes the tunnel as your browser launches, before you open the first page. There is no unprotected window between \"browser open\" and \"VPN on\"."),
            ("Reconnect after every drop",
             "Laptops sleep, Wi-Fi switches to hotspots, trains go through tunnels. Each time, VPNsterr re-establishes the connection on its own — and with the Kill Switch holding the line in between, nothing leaks while it happens."),
            ("Set once, forget forever",
             "Auto-connect, kill switch and your preferred location are remembered locally in your browser. The whole point of the design is that after the first minute of setup, you never think about the VPN again."),
        ],
        "bullets": [
            "Connects automatically when the browser starts",
            "Auto-reconnect after sleep, network switches and drops",
            "Pairs with the Kill Switch — no unprotected gaps",
            "Preferences stored locally in your browser",
            "On both free and Premium",
        ],
        "faq": [
            ("Does auto-connect slow down browser startup?",
             "No — the tunnel is established in parallel while the browser opens, typically within a second."),
            ("Can I choose which location it auto-connects to?",
             "Yes: your last location, a fixed favorite, or Auto (fastest server)."),
        ],
        "keywords": "vpn auto connect, vpn auto reconnect, always on vpn",
    },
    "support": {
        "name": "24/7 Live Support",
        "icon": "headset",
        "hue": "teal",
        "meta_title": "24/7 VPN Support — Real Humans, Fast Answers | VPNsterr",
        "meta_description": "Stuck at 3am? VPNsterr support is real humans around the clock — answers in minutes, not days. Free users included.",
        "h1": "Real humans, around the clock",
        "intro": "VPN problems don't keep office hours — they happen at the airport, before the match starts, in the middle of the night. VPNsterr support is staffed by people 24/7, and we answer in minutes, not days.",
        "sections": [
            ("What you can expect",
             "Median first response is measured in minutes. The person answering can actually fix things — reset a device slot, chase a payment, walk through a connection issue — instead of pasting help-center links."),
            ("Free users get support too",
             "Most VPNs wall support behind the paywall. Our free-tier users get help as well — because a free user with a solved problem is tomorrow's Premium subscriber, and because it's the right thing to do. Premium adds priority queueing."),
            ("Privacy in support too",
             "Support can see your subscription status — never your browsing. There's nothing else to look up: the zero-log architecture applies to our own staff as much as to outsiders."),
        ],
        "bullets": [
            "24/7 human coverage — no chatbot dead-ends",
            "Answers in minutes, not days",
            "Free-tier users included; Premium gets priority",
            "Support staff cannot see your activity — there are no logs",
            "Email: support@vpnsterr.com",
        ],
        "faq": [
            ("How do I contact support?",
             "Email support@vpnsterr.com any time. Premium users are answered with priority."),
            ("Can support see what I browse?",
             "No. Support tooling exposes subscription status only. Browsing activity is never recorded anywhere, so no one can look it up."),
        ],
        "keywords": "vpn 24 7 support, vpn live support",
    },
    "webrtc": {
        "name": "WebRTC Leak Block",
        "icon": "eye-off",
        "hue": "sky",
        "meta_title": "WebRTC Leak Protection — Stop Browser IP Leaks | VPNsterr",
        "meta_description": "WebRTC can expose your real IP even with a VPN on. VPNsterr blocks WebRTC leaks in Chrome, Edge and Brave — automatically, on every plan.",
        "h1": "The browser leak most VPNs forget about",
        "intro": "WebRTC — the technology behind in-browser video calls — can quietly hand out your real IP address to any website that asks, even while your VPN is connected. VPNsterr closes that hole automatically.",
        "sections": [
            ("How WebRTC leaks your real IP",
             "WebRTC establishes direct peer-to-peer connections, and to do so it enumerates your network addresses — including your real local and public IP — and can expose them through JavaScript. A one-line script on any website can read them. Your VPN tunnel never sees this exchange, which is why an ordinary VPN doesn't stop it."),
            ("What VPNsterr does about it",
             "The extension intercepts WebRTC's address discovery so websites only ever see the VPN exit address. Calls and video chats keep working — routed through the tunnel like everything else — but the address enumeration that causes leaks is neutralized."),
            ("Check yourself in 10 seconds",
             "Search for any \"WebRTC leak test\", run it with VPNsterr connected, and confirm the only address shown is your VPN exit IP. We encourage every user to verify rather than take our word."),
        ],
        "bullets": [
            "Blocks WebRTC from exposing your real IP",
            "Works in Chrome, Edge, Brave and other Chromium browsers",
            "Video calls keep working — only the leak path is closed",
            "On by default; nothing to configure",
            "Included free on every plan",
        ],
        "faq": [
            ("Will blocking WebRTC break my video calls?",
             "No. Calls continue to work through the VPN; only the address-enumeration behavior that leaks your real IP is blocked."),
            ("Do I need this if I already use a VPN?",
             "Yes — WebRTC leaks happen at the browser layer, outside the tunnel. VPN and WebRTC protection cover different leak paths, which is why we bundle both."),
        ],
        "keywords": "webrtc leak, webrtc vpn leak, stop webrtc leak",
    },
    "split-tunneling": {
        "name": "Split Tunneling",
        "icon": "split",
        "hue": "violet",
        "meta_title": "Split Tunneling VPN — Choose What Routes | VPNsterr",
        "meta_description": "Decide exactly what goes through the VPN and what uses your normal connection. VPNsterr offers split tunneling — down to individual browser tabs.",
        "h1": "You decide what goes through the VPN",
        "intro": "All-or-nothing VPNs force a trade: protect everything and break the things that need your real location, or turn the VPN off and expose everything. Split tunneling ends the trade — you choose what routes through the tunnel.",
        "sections": [
            ("Split tunneling in VPNsterr",
             "In the browser extension, split tunneling works at the tab level: mark a tab as direct and it bypasses the VPN while every other tab stays protected. Whitelist a site you always want direct — your bank, a local delivery app — and the rule persists."),
            ("Why per-tab beats per-app in the browser",
             "Desktop split tunneling routes whole applications. But your browser is one application running twenty different contexts. Tab-level control is the granularity that actually matches how people browse — and it's a level of control most VPN extensions simply don't offer."),
            ("Typical setups",
             "Keep banking and government portals on your real connection while everything else is private. Route only your streaming tab through another country. Test region-specific content in one tab while working locally in another."),
        ],
        "bullets": [
            "Choose exactly what routes through the VPN",
            "Tab-level granularity in the browser extension",
            "Persistent per-site rules",
            "No reconnecting or toggling the whole VPN",
            "Included on free and Premium",
        ],
        "faq": [
            ("What's the difference between split tunneling and per-tab routing?",
             "Per-tab routing is our browser implementation of split tunneling — same concept, applied at the tab level where it's most useful."),
            ("Can I exclude a whole website permanently?",
             "Yes — add it to your direct list once and it always bypasses the tunnel, in every tab."),
        ],
        "keywords": "split tunneling vpn, vpn split tunnel browser",
    },
}
